#=========================================================================
# Plug in DC Retime
#=========================================================================

name: plugin-pt-eco

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - designer-interface.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------
