#=========================================================================
# Plug in DC Retime
#=========================================================================

name: plugin-dc

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - designer-interface.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------
