#=========================================================================
# DFFRAM step
#=========================================================================

name: macros

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - dffram

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------
