#=========================================================================
# DFFRAM step
#=========================================================================

name: macros

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - design.vcs.v 
  - design.spef

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------
