name: rtl

outputs:
  - design.v
  - design.vcs.v

commands: 
  - cat AESTop.v defines.v EICG_wrapper.v chipyard.TestHarness.CryptoConfig.top.v IOCell.v DFFRAM.v DFFRAMBB.v plusarg_reader.v ClockDividerN.sv > outputs/design.v
  - cp outputs/design.v outputs/design.vcs.v
