#=========================================================================
# Plug in DC Retime
#=========================================================================

name: plugin-dc-retime

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - retime.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------
