name: rtl

outputs:
  - design.v
  - design.vcs.v

commands: 
  - cat user_proj_example.v AESTop.v rng_top.sv IOCell.v EICG_wrapper.v PassthroughIOCell.v chipyard.TestHarness.CryptoSynConfig.top.v top.mems.v plusarg_reader.v ClockDividerN.sv > outputs/design.v
  - cp outputs/design.v outputs/design.vcs.v
